# Generated by Django 2.1.7 on 2019-02-23 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History_connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name to the snap', max_length=200)),
                ('picture', models.ImageField(default='PICTURE_DEFAULT_NAME', help_text='Choose a picture', upload_to='')),
                ('select_resolution', models.CharField(choices=[('HD', '1280×720 píxels'), ('FHD', '1920×1080 pixels'), ('QHD', '2560*1440 pixels'), ('UHD', '3840×2160 píxels')], default='FHD', help_text='Pick up the resolution', max_length=1)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
