# Generated by Django 2.1.7 on 2019-02-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='theme',
            field=models.CharField(default=1, help_text='Enter a name ', max_length=200),
            preserve_default=False,
        ),
    ]
