# Generated by Django 2.1.7 on 2019-03-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_theme_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='theme_type',
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
