# Generated by Django 2.1.7 on 2019-02-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_photo_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='theme',
            field=models.IntegerField(help_text='Enter a name ', max_length=200),
        ),
    ]
