# Generated by Django 2.1.7 on 2019-02-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190223_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='select_resolution',
            field=models.CharField(choices=[('HD', '1280×720 píxels'), ('FHD', '1920×1080 pixels'), ('QHD', '2560*1440 pixels'), ('UHD', '3840×2160 píxels')], default='FHD', help_text='Pick up the resolution', max_length=3),
        ),
    ]
