# Generated by Django 2.1.7 on 2019-02-22 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20190222_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='theme',
        ),
        migrations.AddField(
            model_name='photo',
            name='original_resolution',
            field=models.CharField(help_text='Enter the resolution of the photo', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='select_resolution',
            field=models.CharField(choices=[('HD', '1280×720 píxels'), ('FHD', '1920×1080 pixels'), ('QHD', '2560*1440 pixels'), ('UHD', '3840×2160 píxels')], default='FHD', help_text='Pick up the resolution', max_length=1),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='Anonymous', help_text='Enter a name', max_length=200),
        ),
    ]
