# Generated by Django 2.1.7 on 2019-02-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20190222_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='picture',
            field=models.ImageField(default='https://www.telsa.com.mx/sites/default/files/default_images/default_picture_0.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='history_connections',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
