# Generated by Django 2.1.7 on 2019-03-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20190223_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='picture',
        ),
        migrations.AddField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='select_resolution',
            field=models.CharField(choices=[('HD', '1280×720 píxels'), ('FHD', '1920×1080 pixels'), ('QHD', '2560*1440 pixels'), ('UHD', '3840×2160 pixels')], default='FHD', max_length=3),
        ),
    ]
