# Generated by Django 2.1.7 on 2019-02-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20190222_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='original_resolution',
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(help_text='Enter a name to the snap', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(default='PICTURE_DEFAULT_NAME', help_text='Choose a picture', upload_to=''),
        ),
    ]
