# Generated by Django 2.1.7 on 2019-03-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20190303_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumb',
        ),
        migrations.AddField(
            model_name='photo',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
