# Generated by Django 2.1.7 on 2019-03-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_photo_select_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
