# Generated by Django 2.1.7 on 2019-03-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_connections',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(help_text='Enter a name to the snap', max_length=64),
        ),
        migrations.AlterField(
            model_name='photo',
            name='select_resolution',
            field=models.CharField(choices=[('HD', '1280×720 píxels'), ('FHD', '1920×1080 pixels'), ('QHD', '2560*1440 pixels'), ('UHD', '3840×2160 pixels')], default='FHD', max_length=4),
        ),
        migrations.AlterField(
            model_name='photo',
            name='select_theme',
            field=models.CharField(choices=[('NATURE', 'NATURE'), ('URBAN', 'URBAN'), ('OTHER', 'OTHER'), ('SELECT', 'SELECT')], default='SELECT', max_length=16),
        ),
    ]
